library(summarytools)
library(psych)
library(skimr)

summary(desvio_inflacao_dataframe$desvios)
summary(hiato$hiato)
#summary(hiato$hiato)
summary(CAMBIO$value)
summary(EMBI$EMBI_media)
summary(DIVIDA_LIQUIDA$DIVIDA_LIQUIDA)
summary(SELIC$SELIC)
summary(SELIC$SELIC_defasado)
summary(COMODITIES$value)
