library(summarytools)
library(psych)
library(skimr)

summary(desvio_inflacao_dataframe$desvios)
summary(hiato_percentual$hiato)
#summary(hiato$hiato)
summary(CAMBIO$retorno_cambio)
summary(EMBI$EMBI_media)
summary(DIVIDA_LIQUIDA$variacao_percentual)
